### ISSUE TITLE
Exception: Window with id GCoverage isn't registered

### ISSUE THREAD

**Issue by SimonG96** [zero9178/C-Cpp-Coverage-for-CLion#5]
When running the Coverage I get the following CLion exception:

`java.lang.Throwable: window with id="GCoverage" isn't registered`

The following warnings are shown in the Event Log:

- `stamp mismatch with notes file`
- `source file is newer than notes file`

Coverage results are shown correct in the editor but the GCoverage window is not opened.
I also can't open the window manually over `View->ToolWindows->GCoverage`, the option is greyed out.

CLion: CLion 2019.1 EAP, Build #CL-191.6014.11
GCoverage: v1.1.3

Stacktrace:

```
 java.lang.Throwable: window with id="GCoverage" isn't registered
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.getRegisteredInfoOrLogError(ToolWindowManagerImpl.java:681)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.java:886)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindow(ToolWindowManagerImpl.java:793)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.show(ToolWindowImpl.java:187)
	at gcov.window.GCovWindowFactory.lambda$null$0(GCovWindowFactory.java:62)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:723)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:672)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:367)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by tmaierhofer** [comment]
Uninstalling and Reinstalling of the Plugin fixed the Issue for me
